name: Laravel Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Laravel Application
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S sh -c 'cd /var/www/html && sudo git pull origin master'

        
