name: Git Pull and Artisan Commands

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run_pull:
    name: Run Pull and Artisan Commands
    runs-on: ubuntu-latest
    
    steps:
    - name: Install sshpass
      run: sudo apt update && sudo apt install -y sshpass
      
    - name: Create password file
      run: echo "Elam@1234" > /tmp/password.txt
      
    - name: Connect and Pull
      run: |
        sshpass -f /tmp/password.txt ssh -tt elam@3.80.122.51 << EOF
        # Commands to run on the remote server
        cd /path/to/your/directory
        git pull
        php artisan migrate
        # Add more commands as needed
        EOF


