name: Laravel

on:
  push:
    branches: [ "master" ]


jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    steps:
     - name: Deploy Mentor Application
       uses: appleboy/ssh-action@v0.1.2
       with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWD }}
        script: |
          cd /var/www/html
          sudo git pull origin master
 
