name: Git Pull and Artisan Commands

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run_pull:
    name: Run Pull and Artisan Commands
    runs-on: ubuntu-latest
    
    steps:
    - name: Install sshpass
      run: sudo apt update && sudo apt install -y sshpass
      
    - name: Connect and Pull
      run: |
        sshpass -p "Elam@1234" ssh elam@3.80.122.51 'cd /var/www/html/phpapp && sudo git pull origin master && sudo php artisan cache:clear && sudo php artisan view:clear && sudo php artisan config:clear && sudo php artisan route:clear'
